[build]
  command = "npm i --verbose && strip --strip-debug ./node_modules/couchbase/build/Release/couchbase_impl.node"
  publish = "."
  
  [template.environment]
  COUCHBASE_USERNAME = "COUCHBASE_USERNAME"
  COUCHBASE_PASSWORD = "COUCHBASE_PASSWORD"
  COUCHBASE_ENDPOINT = "COUCHBASE_ENDPOINT"
  COUCHBASE_BUCKET = "COUCHBASE_BUCKET"